# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: sqlite3
  database: library_development
  username: root
  password: 
  host: localhost
test:
  adapter: sqlite3
  database: library_test
  username: root
  password: 
  host: localhost


production: 
adapter: sqlite3
encoding: unicode
host: localhost
database: cnh_production
pool: 5
username:
password: 